### ISSUE TITLE
numbers w/ decimal points are matched incorrectly

### ISSUE THREAD

**Issue by p-gega** [lbechberger/CorpusStudyNumerals#13]
example: 

numbers_regex = re.compile(r'\b(\d+(?:\,\d\d\d)*)\b')
sentence = '8.3 million illegal immigrants'
numbers_regex.findall(sentence)
>> ['8', '3']

**Comment by p-gega** [comment]
can \s be used instead of \b or does this cause other trouble?

**Comment by p-gega** [comment]
problem does not really occur if prefix and postfix are used: RegEx matches 8 -> number is just "floor-ed" (ignore that the example is a mixed numeral, it was chosen badly).

**Comment by lbechberger** [comment]
According to the https://docs.python.org/2/library/re.html entry about \s: "it matches any whitespace character, this is equivalent to the set [ \t\n\r\f\v]." So I guess this won't work for sentences like "It was quite hot (38 °C, to be specific).", where the number is preceded by an opening parenthesis and not by whitespace.

Maybe we can modify the regex internally to also match the decimal part? I think this should be possible in a way similar to how we deal with the thousandsSeparator. If you then cast the whole thing to integer, you should also simply drop the decimal part.
