### ISSUE TITLE
Numbers at the beginning of a sentence

### ISSUE THREAD

**Issue by lbechberger** [lbechberger/CorpusStudyNumerals#5]
Make sure that numbers at the very beginning of a sentence are taken into account.

Example: "54321 people participated in the survey."

**Comment by krumnack** [comment]
Ok, I fixed this now (using some ugly construct) - and added a test ` test_number_at_beginning` to `EnglishTest`.

@lbechberger: however, it would be nice if we could explain why we need pre- and postfixes. I put some question into the [code](https://github.com/lbechberger/CorpusStudyNumerals/blob/05523919d0495f79eccd70af44b18e9b5a75fc65/numerals/languages.py#L53). It would be good if you could answer that and then close this issue.

**Comment by lbechberger** [comment]
Turns out we don't need the pre- and postfixes if we use \b in the regex. I've changed the code accordingly and have added some tests making sure that this doesn't do any harm.
